segmentation_model: unet
encoder_name: resnet50
encoder_weights: imagenet
learning_rate: 0.001
in_channels: 3
num_classes: 4
learning_rate_schedule_patience: 10
loss: ce
ignore_zeros: null
imagenet_pretraining: true
